// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXqhLTIx7UECXHFO0pvP_Ap0RGxZmdly8',
    appId: '1:461945687295:web:d2da9ade1a4ec0c3f050ca',
    messagingSenderId: '461945687295',
    projectId: 'eventify202530',
    authDomain: 'eventify202530.firebaseapp.com',
    storageBucket: 'eventify202530.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk_YVmCAuYMqLwXPkTp-_xHSgsrDqoXww',
    appId: '1:461945687295:android:65cfe4c7fdba046bf050ca',
    messagingSenderId: '461945687295',
    projectId: 'eventify202530',
    storageBucket: 'eventify202530.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrPAO_e82_TEG6MXu7pds16oT4BCHUql0',
    appId: '1:461945687295:ios:ff0912636b689479f050ca',
    messagingSenderId: '461945687295',
    projectId: 'eventify202530',
    storageBucket: 'eventify202530.firebasestorage.app',
    iosBundleId: 'com.ae.eventify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrPAO_e82_TEG6MXu7pds16oT4BCHUql0',
    appId: '1:461945687295:ios:ff0912636b689479f050ca',
    messagingSenderId: '461945687295',
    projectId: 'eventify202530',
    storageBucket: 'eventify202530.firebasestorage.app',
    iosBundleId: 'com.ae.eventify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXqhLTIx7UECXHFO0pvP_Ap0RGxZmdly8',
    appId: '1:461945687295:web:8b353cce1ad73558f050ca',
    messagingSenderId: '461945687295',
    projectId: 'eventify202530',
    authDomain: 'eventify202530.firebaseapp.com',
    storageBucket: 'eventify202530.firebasestorage.app',
  );
}
